ci - upload built packages to github release

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -48,12 +48,28 @@ jobs:
     # Checkout repository --------------------------------------------------------------------
     - uses: actions/checkout@v2
 
+    # Checkout release tag (if on release branch)
+    - name: Checkout release tag (if on release branch)
+      if: github.ref == 'refs/heads/ci-release'
+      env:
+        GH_TOKEN: ${{ github.token }}
+        IMAGE_NAME: ${{ matrix.image }}
+      run: |
+        git config --global --add safe.directory "$PWD"
+        git fetch --tags
+        latest_tag="$(git tag | grep 'v[0-9]*\.[0-9]*\.[0-9]*' | sort -rn | head -n1)"
+        if [ -z "$latest_tag" ]; then
+          echo "could not find latest tag"
+          exit 1
+        fi
+        git checkout "$latest_tag"
+
     # Build LIBFDS DEB package ---------------------------------------------------------------
     - name: Checkout libfds library - master branch
-      if: github.ref == 'refs/heads/master'
+      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-release'
       run: git clone --branch master https://github.com/CESNET/libfds.git build/libfds_repo
     - name: Checkout libfds library - devel branch
-      if: github.ref != 'refs/heads/master'
+      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/ci-release'
       run: git clone --branch devel https://github.com/CESNET/libfds.git build/libfds_repo
     - name: Build DEBs of libfds library and install them
       working-directory: 'build/libfds_repo'
@@ -85,6 +101,44 @@ jobs:
           build/pkg/deb/debbuild/*.ddeb
           build/pkg/deb/debbuild/*.tar.gz
           build/pkg/deb/debbuild/*.dsc
+
+    - name: Publish DEB packages to GitHub releases (latest)
+      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-publish-packages-to-releases'
+      env:
+        GH_TOKEN: ${{ github.token }}
+        IMAGE_NAME: ${{ matrix.image }}
+      run: |
+        curl -sL "$(curl -sL "https://api.github.com/repos/cli/cli/releases" | grep _linux_amd64.tar.gz | grep https | head -n1 | cut -d'"' -f4)" -o gh.tar.gz \
+          && tar xzf gh.tar.gz \
+          && find gh*/ -name gh -exec mv {} /usr/local/bin/ \;
+        git config --global --add safe.directory "$PWD" \
+          && git tag -f ci-latest HEAD \
+          && git push -f origin tag ci-latest
+        find build/ -iname '*.deb' | while read -r f; do
+          newf="$IMAGE_NAME-$(basename "$f")"
+          mv "$f" "$newf"
+          gh release upload --clobber ci-latest "$newf"
+        done
+
+    - name: Publish DEB packages to GitHub releases (stable)
+      if: github.ref == 'refs/heads/ci-release'
+      env:
+        GH_TOKEN: ${{ github.token }}
+        IMAGE_NAME: ${{ matrix.image }}
+      run: |
+        curl -sL "$(curl -sL "https://api.github.com/repos/cli/cli/releases" | grep _linux_amd64.tar.gz | grep https | head -n1 | cut -d'"' -f4)" -o gh.tar.gz \
+          && tar xzf gh.tar.gz \
+          && find gh*/ -name gh -exec mv {} /usr/local/bin/ \;
+        latest_tag="$(git describe --exact-match --tags)"
+        if ! gh release view "$latest_tag"; then
+          echo "could not find release for tag $latest_tag"
+          exit 1
+        fi
+        find build/ -iname '*.deb' | while read -r f; do
+          newf="$IMAGE_NAME-$(basename "$f")"
+          mv "$f" "$newf"
+          gh release upload --clobber "$latest_tag" "$newf"
+        done
 
   rpm:
     # Try to build RPM packages
@@ -153,12 +207,28 @@ jobs:
     # Checkout repository --------------------------------------------------------------------
     - uses: actions/checkout@v2
 
+    # Checkout release tag (if on release branch)
+    - name: Checkout release tag (if on release branch)
+      if: github.ref == 'refs/heads/ci-release'
+      env:
+        GH_TOKEN: ${{ github.token }}
+        IMAGE_NAME: ${{ matrix.image }}
+      run: |
+        git config --global --add safe.directory "$PWD"
+        git fetch --tags
+        latest_tag="$(git tag | grep 'v[0-9]*\.[0-9]*\.[0-9]*' | sort -rn | head -n1)"
+        if [ -z "$latest_tag" ]; then
+          echo "could not find latest tag"
+          exit 1
+        fi
+        git checkout "$latest_tag"
+
     # Build LIBFDS RPM package ---------------------------------------------------------------
     - name: Checkout libfds library - master branch
-      if: github.ref == 'refs/heads/master'
+      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-release'
       run: git clone --branch master https://github.com/CESNET/libfds.git build/libfds_repo
     - name: Checkout libfds library - devel branch
-      if: github.ref != 'refs/heads/master'
+      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/ci-release'
       run: git clone --branch devel https://github.com/CESNET/libfds.git build/libfds_repo
     - name: Build RPMs of libfds library and install it
       working-directory: 'build/libfds_repo'
@@ -203,3 +273,41 @@ jobs:
         path: |
           build/pkg/rpm/rpmbuild/RPMS/
           build/pkg/rpm/rpmbuild/SRPMS/
+
+    - name: Publish RPM packages to GitHub releases (latest)
+      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-publish-packages-to-releases'
+      env:
+        GH_TOKEN: ${{ github.token }}
+        IMAGE_NAME: ${{ matrix.image }}
+      run: |
+        curl -sL "$(curl -sL "https://api.github.com/repos/cli/cli/releases" | grep _linux_amd64.tar.gz | grep https | head -n1 | cut -d'"' -f4)" -o gh.tar.gz \
+          && tar xzf gh.tar.gz \
+          && find gh*/ -name gh -exec mv {} /usr/local/bin/ \;
+        git config --global --add safe.directory "$PWD" \
+          && git tag -f ci-latest HEAD \
+          && git push -f origin tag ci-latest
+        find build/ -iname '*.rpm' | while read -r f; do
+          newf="$IMAGE_NAME-$(basename "$f")"
+          mv "$f" "$newf"
+          gh release upload --clobber ci-latest "$newf"
+        done
+
+    - name: Publish RPM packages to GitHub releases (stable)
+      if: github.ref == 'refs/heads/ci-release'
+      env:
+        GH_TOKEN: ${{ github.token }}
+        IMAGE_NAME: ${{ matrix.image }}
+      run: |
+        curl -sL "$(curl -sL "https://api.github.com/repos/cli/cli/releases" | grep _linux_amd64.tar.gz | grep https | head -n1 | cut -d'"' -f4)" -o gh.tar.gz \
+          && tar xzf gh.tar.gz \
+          && find gh*/ -name gh -exec mv {} /usr/local/bin/ \;
+        latest_tag="$(git describe --exact-match --tags)"
+        if ! gh release view "$latest_tag"; then
+          echo "could not find release for tag $latest_tag"
+          exit 1
+        fi
+        find build/ -iname '*.rpm' | while read -r f; do
+          newf="$IMAGE_NAME-$(basename "$f")"
+          mv "$f" "$newf"
+          gh release upload --clobber "$latest_tag" "$newf"
+        done
